FROM node:16

WORKDIR /app

# Установка MySQL клиента
RUN apt-get update && apt-get install -y default-mysql-client

# Копируем зависимости сервера
COPY server/package*.json ./

RUN npm install

# Копируем остальные файлы сервера
COPY server/ .

EXPOSE 5005
CMD ["npx", "nodemon", "index.js"]