services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: cosmetic_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      timeout: 10s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'  # Доступ через http://localhost:8080
    environment:
      PMA_HOST: mysql  # Связь с сервисом mysql
      MYSQL_ROOT_PASSWORD: test123  # Пароль должен совпадать с mysql
    depends_on:
      - mysql  # Запускать только после mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '5005:5005'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: test123
      DB_NAME: cosmetic_db
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mysql-data: