version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: cosmetic_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 10s
      retries: 10

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    entrypoint: npm start

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '5005:5005'
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    command: ['npx', 'nodemon', 'index.js']

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test123

volumes:
  mysql-data:
