
# Используем официальный образ Node.js
FROM node:16

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем default-mysql-client
RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

# Копируем package.json и package-lock.json
COPY server/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Открываем порт, на котором работает сервер
EXPOSE 5005

# Запускаем сервер с nodemon
CMD ["npx", "nodemon", "index.js"]